---
abstract: 'A simple tree object'
author:
  - 'Stevan Little <stevan@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.06, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tree-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '1.18'
  Test::Exception: '0.15'
  Test::More: '1.001014'
  constant: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tree-Simple
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.26'

