---
abstract: 'A simple tree object'
author:
  - 'Stevan Little, E<lt>stevan@iinteractive.comE<gt>'
  - 'Rob Kinyon, E<lt>rob@iinteractive.comE<gt>'
  - 'Ron Savage E<lt>ron@savage.net.auE<gt> has taken over maintenance as of V 1.19.'
build_requires:
  Test::Exception: 0.15
  Test::More: 0.47
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-Simple
provides:
  Tree::Simple:
    file: lib/Tree/Simple.pm
    version: 1.19
  Tree::Simple::Visitor:
    file: lib/Tree/Simple/Visitor.pm
    version: 1.19
requires:
  Scalar::Util: 1.18
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.19
