---
abstract: 'A simple tree object'
author:
  - 'Stevan Little <stevan@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0.15'
  Test::More: '1.001002'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.22, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tree-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '1.18'
  constant: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tree-Simple
  license: http://dev.perl.org/licenses/
  repository: https://github.com/ronsavage/Tree-Simple.git
version: '1.31'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
